### PR TITLE
run CI on modern python

### PR DESCRIPTION
**Pull request by phobson**

### CODE REVIEW

**Comment by phobson** [comment]
@austinorr I can't merge here any more :( 

fair, but could I get a merge here and and push v0.1.0 tag to get a new pypi release (should be automatic through GitHub CI)

**Comment by austinorr** [comment]
Merged, will release tomorrow or Tuesday, is that soon enough or is this release blocking you?

**Comment by phobson** [comment]
Thanks! Not a substantial blockers. I just wanted mess around with making a dask implementation that relies on the guts of this library, *and* I'm finally getting around to kicking the tires on packaging with `poetry`.

**Comment by austinorr** [comment]
@phobson so pypi lists v0.1 as the current release, though our prior releases here on the repo don't quite match up. Can I push a new release that's at 0.2.0 with the repo tag matching the release & version tag? I think dropping old python version tests/support call for at least a minor bump to 0.2. The previous repo tags were descriptive, but not semantic version compliant yet, so we can start that practice with this release too.

I'm in full support of poetry, fwiw. It seems to be where many new projects are gellin these days. It's a shame that python packaging has not found a way to upstream these offshoot projects, but it's nice that the pyproject.toml has started to eat the world and replace setup.cfg & setup.py as a standard.

**Comment by phobson** [comment]
Oh yeah, I see that, @austinorr. Strange. v0.2.0 is good for me

**Comment by austinorr** [comment]
@phobson, you've been re-added as a maintainer!

**Pull request merged**
