### PR TITLE
fixes #30 by making plotting api return axes objects rather than figures

### LINKED ISSUE #30: Feature: well-behaved plotting API
when working in jupyter notebook, the current `viz` api produces matplotlib.figure() instances from the plotting functions. These figures cannot be shown without building a backend handler ala `FigureCanvas` and do not play nice with the %matplotlib inline magic.

One useful plotting pattern is to either allow the user to build the figure and the axes instances with `matplotlib.pyplot.subplots()` or equivalent and then pass the axes objects to our function, or if an axes is not provided, make one for them and display the result. In the current implementation, and in the first example of the readme, the following will error: `fig = cloudside.viz.windrose(data)` since the axes is a required kwarg with no fallback.

A PR with a well-behaved plotting API is forthcoming which solves this limitation. The solution is to utilize `pyplot` to build the axes objects if none are provided. importing `pyplot` can annoy automated tests since it sets the backend itself, but if the test script simply imports `cloudside` after setting `matplotlib.use('agg')` then there should be no issues (and die-hard pep8 adherents can rest easy since the offending out of order assignment and import is only in the `check_cloudside.py` script and not in the library.).

The existing behavior means that a user could never make a figure with two rows of rainclocks, since the plotting function builds the `figure()` object. It also means that none of the figures built by the library are able to be shown inline in a notebook since they were't built with pyplot.

### PR DESCRIPTION
**Pull request by austinorr**
this PR allows the user to do the following if they want:
```
import matplotlib.pyplot as plt
from cloudside import viz
from cloudside.tests.test_viz import test_data

fig, axes = plt.subplots(2,2,figsize=(20,20), subplot_kw=dict(polar=True))
axes12 = viz.rain_clock(test_data(), raincol='Precip', axes=axes.ravel()[:2])
axes34 = viz.rain_clock(test_data(), raincol='Precip', axes=axes.ravel()[2:])
```
it also means that the example in the docs:
```
import cloudside
data = cloudside.asos.get_data('KPDX', '2012-12-01', '2015-05-01', email='youremail@wherever.com')
cloudside.viz.rose(data, 'wind_speed', 'wind_direction')
```
will actually show something when run in `jupyter`.

### CODE REVIEW

**Comment by austinorr** [comment]
CI failure is unrelated to the plotting changes (they checkout locally). I think it's a `pandas` issue stemming from #29 due to an upstream change in the `df.apply()` function.

**Comment by phobson** [comment]
This is library/API approach and issue that I've been struggling with for a while.

According to the veteran MPL devs, it's **best** (not critical) that downstream libraries not import pyplot. This is because all of baggage/configs/statefullness that comes with pyplot.

So if you start with this in a notebook:

```python
%matplotlib inline
import tempfile
from matplotlib import pyplot
from cloudside import asos, viz

with tempfile.TemporaryDirectory() as rawdir:
    df = asos.get_data('KPDX', '2018-01-01', '2018-03-01',
                       'phobson@geosyntec.com', folder=rawdir)
```

And then you do this:
```python
viz.rose(df, 'wind_speed', 'wind_direction', ax=None)
```

Do you get an error. But you don't get an error if you do this:
```python
fig, ax = pyplot.subplots(subplot_kw=dict(polar=True))
fig, rose = viz.rose(df, 'wind_speed', 'wind_direction', ax=ax)
```

On some level, I'd like to just make `ax` a required parameter and keep cloudside free from pyplot imports. However, that's a pain with e.g., windroses since the user has to go out of their way to make a polar axes object.

**Comment by austinorr** [comment]
One issue is that the following cannot produce any graphical output on `jupyter` in the current code-base: 
```
from cloudside import viz
from cloudside.tests.test_viz import test_data
fig = viz.rain_clock(test_data, raincol='Precip')
```
granted that rain clock is not the purpose for this library, but it's illustrative of the limitations of having the library steer clear of `pyplot`. The disadvantage here is that this `fig` object cannot be shown until the user writes their own backend handler, e.g.:
```
from matplotlib.backends import backend_qt4agg
backend_qt4agg.new_figure_manager_given_figure(1, fig)
fig.show()
```
If this lib should be free of a `pyplot` import (which is a reasonable idea, `pyplot` is really complex) then there should be no `axes_object` validator function, and every plotting function should take a required axes object, or list of objects in the rain clocks case, and return the axes rather than the figures. Note that there is currently no code in the library that actually needs any of the mpl.figure.Figure() instances that are created during use of the plotting helper functions, except to ensure that the functions have something to return.

One other way that might be nice is to move the `pyplot` import into the `axes_object` validator and import it only if no axes is provided. This would prevent the `cloudside` lib from interacting with the 'state' of the `pyplot` params since it'd be loaded long after the user imports things as they like and sets their own rc params. This would make it possible for the code to handle the `ax=none` case _and_ return `mpl` objects that can be shown via `plt.show()` or `%matplotlib inline`

**Comment by phobson** [comment]
I've thought about this.

Here's what I think:
  * make the axes required params, except for `rain_clock`
  * for `rain_clock`, call the axes parameters `am_ax` and `pm_ax` are optional, but at least 1 has to be there. this way the user could split them up between separate figure if need be.
  * return (dictionaries of?) artists instead of the axes or figures.

**Comment by austinorr** [comment]
Closing -- need to see if this is still an issue 4 years later. Will open new issue if needed.

**Pull request closed without merging**
